# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pm_ante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_id', models.IntegerField(null=True)),
                ('ante', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pm_blind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_id', models.IntegerField(null=True)),
                ('bigblind', models.CharField(max_length=20)),
                ('blind_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pm_gamepeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(null=True)),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pm_gametime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_id', models.IntegerField(null=True)),
                ('time_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pm_gametype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(null=True)),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pm_op_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type_id', models.IntegerField(null=True)),
                ('op_type_name', models.CharField(max_length=20)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
            ],
        ),
        migrations.CreateModel(
            name='real_account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='real_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tmp_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('game_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tmp_result_step_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=20)),
                ('income_rate', models.IntegerField()),
                ('insure_rate', models.IntegerField()),
                ('game_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tmp_result_step_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('score_final', models.IntegerField()),
                ('income_rate', models.IntegerField()),
                ('income', models.IntegerField()),
                ('game_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tmp_result_step_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('club_name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('score_final', models.IntegerField()),
                ('income_water', models.IntegerField()),
                ('waterup', models.IntegerField()),
                ('insure', models.IntegerField()),
                ('income_insure', models.IntegerField()),
                ('insure_up', models.IntegerField()),
                ('income_total', models.IntegerField()),
                ('up_total', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('game_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ucs_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('chance', models.IntegerField(null=True)),
                ('chance_desc', models.CharField(max_length=20)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
                ('operator_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ucs_club_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_gameno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametime', models.DateTimeField(auto_now=True)),
                ('cnt', models.IntegerField(null=True)),
                ('game_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ucs_gamerecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.CharField(max_length=20)),
                ('game_type', models.CharField(max_length=10)),
                ('blind', models.CharField(max_length=10)),
                ('ante', models.CharField(max_length=10)),
                ('playercnt', models.IntegerField()),
                ('buyin', models.IntegerField(null=True)),
                ('duration', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('status_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('operator_id', models.IntegerField(null=True)),
                ('inactivetime', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_subs_club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=20)),
                ('club_shortname', models.CharField(max_length=4)),
                ('club_desc', models.CharField(max_length=80)),
                ('income_rate', models.IntegerField()),
                ('insure_rate', models.IntegerField()),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_subs_user',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('customer_id', models.IntegerField(null=True)),
                ('account_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('wx_name', models.CharField(max_length=20)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-1-1')),
                ('operator_id', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=40)),
            ],
        ),
    ]
