# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_ante',
            name='type_desc',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pm_blind',
            name='type_desc',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pm_gametype',
            name='type_desc',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
