# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0002_auto_20171211_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_gamerecord',
            name='cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
