# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0005_remove_ucs_gamerecord_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_game_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
