# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0006_pm_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_gamerecord',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
