# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0007_ucs_gamerecord_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucs_gamerecord',
            name='group_id',
        ),
        migrations.AddField(
            model_name='ucs_gamerecord',
            name='group_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
