# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0010_auto_20171212_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ucs_club_balance',
        ),
    ]
