# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0011_delete_ucs_club_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_club_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=25)),
                ('account_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('chance_type', models.IntegerField(null=True)),
                ('chance_desc', models.CharField(max_length=20)),
                ('operator_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
                ('note', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='ucs_subs_club',
            name='account_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
