# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0015_ucs_union_account_ucs_union_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_club_balance',
            name='serial_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ucs_union_balance',
            name='serial_no',
            field=models.CharField(max_length=30),
        ),
    ]
