# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0016_auto_20171214_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_club_lever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lever_id', models.IntegerField()),
                ('lever_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ucs_subs_club',
            name='club_lever',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
