# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0017_auto_20171218_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_club_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('subs_club_id', models.IntegerField()),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
