# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0021_remove_ucs_result_table_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_comany_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_company_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('serial_no', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('op_type_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
