# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0022_pm_comany_type_ucs_company_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_company_balance',
            name='note',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
