# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0023_ucs_company_balance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_company_balance',
            name='op_account_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
