# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0024_ucs_company_balance_op_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_balance',
            name='type_id',
            field=models.IntegerField(null=True),
        ),
    ]
