# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0026_ucs_union_balance_main_club_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_company_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('water', models.IntegerField()),
                ('insure', models.IntegerField()),
                ('up_water', models.IntegerField()),
                ('up_insure', models.IntegerField()),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
