# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0029_ucs_result_table_l1_l1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucs_result_table_l1',
            old_name='l1',
            new_name='level',
        ),
        migrations.AddField(
            model_name='ucs_result_table_l1',
            name='main_club_id',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
