# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0032_ucs_result_table_l2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_club_relation',
            name='club_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
