# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0033_ucs_club_relation_club_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_union_balance_l1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30)),
                ('account_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('chance_type', models.IntegerField(null=True)),
                ('chance_desc', models.CharField(max_length=20)),
                ('operator_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
                ('note', models.CharField(max_length=80)),
                ('main_club_id', models.IntegerField()),
            ],
        ),
    ]
