# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0034_ucs_union_balance_l1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_club_developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('developer_id', models.IntegerField()),
                ('active_time', models.DateTimeField()),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.IntegerField()),
                ('developer_name', models.CharField(max_length=20)),
                ('developer_desc', models.CharField(max_length=40)),
                ('income_rate', models.IntegerField()),
                ('insure_rate', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
