# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0035_ucs_club_developer_ucs_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_club_developer',
            name='club_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
