# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0036_ucs_club_developer_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_club_developer',
            name='active_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
