# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0037_auto_20171226_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('permission', models.CharField(max_length=20)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_permission_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
