# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0038_pm_permission_ucs_permission_ucs_permission_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddy_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
