# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0039_paddy_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucs_permission',
            old_name='inactive_time',
            new_name='inactive_tme',
        ),
        migrations.AddField(
            model_name='ucs_operator',
            name='permission_group',
            field=models.IntegerField(null=True),
        ),
    ]
