# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0040_auto_20171226_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucs_permission',
            old_name='inactive_tme',
            new_name='inactive_time',
        ),
    ]
