# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0042_auto_20171227_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_result_table_l1',
            name='developer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ucs_result_table_l2',
            name='developer_id',
            field=models.IntegerField(null=True),
        ),
    ]
