# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0044_auto_20171229_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=20)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ucs_game_reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
