# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0045_pm_reward_ucs_game_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pm_comany_type',
            new_name='pm_company_type',
        ),
    ]
