# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0048_pm_deposit_status_ucs_deposit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_deposit_balance',
            name='serial_no',
            field=models.CharField(max_length=40),
        ),
    ]
