# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0049_auto_20180102_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_club_account',
            name='account_desc',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
