# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0050_ucs_club_account_account_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_deposit_balance',
            name='account_target_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
