# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0051_ucs_deposit_balance_account_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_operator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
