# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0052_ucs_operator_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_gamerecord',
            name='img_url',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
