# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0053_ucs_gamerecord_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucs_credit_account',
            name='user_id',
        ),
    ]
