# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0054_remove_ucs_credit_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_credit_account',
            name='inactive_time',
            field=models.DateTimeField(default='2037-01-01'),
        ),
    ]
