# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0055_auto_20180113_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_credit_developer_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('credit_num', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('note', models.CharField(max_length=80)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
