# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0056_ucs_credit_developer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_developer_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=40)),
                ('developer_id', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('chance', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('note', models.CharField(max_length=40)),
                ('active_time', models.DateTimeField(auto_now_add=True)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
