# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0061_ucs_club_user_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_subs_user',
            name='note',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
