# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0062_auto_20180119_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_result_table_l1',
            name='active_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 23, 9, 14, 222407)),
        ),
    ]
