# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0069_auto_20180122_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_result_table_l2',
            name='active_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
