# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0071_auto_20180122_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_tree_l1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('tree_desc', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=80)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='menu_tree_l2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('tree_desc', models.CharField(max_length=40)),
                ('paerent_id', models.IntegerField()),
                ('url', models.CharField(max_length=80)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='permission_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('tree_l1_id', models.IntegerField()),
                ('tree_l2_id', models.IntegerField()),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
