# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0072_menu_tree_l1_menu_tree_l2_permission_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu_tree_l1',
        ),
        migrations.DeleteModel(
            name='menu_tree_l2',
        ),
        migrations.DeleteModel(
            name='permission_menu',
        ),
    ]
