# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0075_auto_20180124_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_tree_l2',
            old_name='paerent_id',
            new_name='parent_id',
        ),
    ]
