# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0076_auto_20180124_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucs_game_reward_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.CharField(max_length=30)),
                ('file_url', models.CharField(max_length=20)),
                ('club_id', models.IntegerField()),
                ('blind_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
