# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0078_auto_20180129_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_game_reward',
            name='club_id',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
