# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0080_ucs_club_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucs_club_user',
            name='feedback_type',
            field=models.IntegerField(default=0),
        ),
    ]
