# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0083_remove_ucs_result_table_l2_tmp_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucs_company_balance',
            name='op_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
