# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdt', '0084_auto_20180210_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField()),
                ('op_type_id', models.IntegerField(null=True)),
                ('op_desc', models.CharField(max_length=100)),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ucs_balance',
            name='updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
