"""demo1_1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from sdt.views import *
app_name='sdt'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^club/', club_list),
    url(r'^club_add/', club_add),
    url(r'^checkclub/', checkclub),
    url(r'^user/',user),
    url(r'^checkuser/',checkuser),
    url(r'^user_list/',user_list),
    url(r'^user_add/',user_add),
    url(r'^old_user_add/',old_user_add),
    url(r'^cash/',cash),
    url(r'^getbalance/',getbalance),
    #url(r'^cashin/',cashin),
    url(r'^result/$', result),
    url(r'^result_pretreat_step1/', result_pretreat_step1),
    url(r'^result_newuser/', result_newuser),
    url(r'^result_club/', result_club),
    url(r'^table/', loadtabletype),
    url(r'^getante/', getante),
    url(r'^table_list/', table_list),
    url(r'^game_reg/', game_reg),
    url(r'^result_preview/$', result_preview),
    url(r'^result_view/', result_view),
    url(r'^result_l1/', result_l1),
    url(r'^result_post/', result_post),
    url(r'^result_union/', result_union),
    url(r'^result_unionbyclub/', result_unionbyclub),
    url(r'^useraccountview/', useraccountview),
    url(r'^usercash/', usercash),
    url(r'^login/', login),
    url(r'^default/', default),
    url(r'^report_view/', report_view),
    url(r'^operator/', operator),
    url(r'^add_operator_group/', add_operator_group),
    url(r'^operator_group_list/', operator_group_list),
    url(r'^operator_list/', operator_list),
    url(r'^add_operator/', add_operator),
    url(r'^operator_setup/', operator_setup),
    url(r'^operator_relation/', operator_relation),
    url(r'^operator_relation_setup/', operator_relation_setup),
    url(r'^relation_list/', relation_list),
    url(r'^club_account_info/', club_account_info),
    url(r'^check_balance/', check_balance),
    url(r'^test/', test),
    url(r'^test02/', test02),
    url(r'^searchUser/', searchUser),
    url(r'^modify_user/', modify_user),
    url(r'^modifyUserInfo/', modifyUserInfo),
    url(r'^user_account_group/', user_account_group),
    url(r'^user_group_search/', user_group_search),
    url(r'^account_migrate/', account_migrate),
    url(r'^club_manage/', club_manage),
    url(r'^club_info/', club_info),
    url(r'^modify_club/', modify_club),
    url(r'^table_reg_mini/', table_reg_mini),
    url(r'^getusefulbalance/', getusefulbalance),
    url(r'^userbuyin/', userbuyin),
    url(r'^freeze_minilist/', freeze_minilist),
    url(r'^abortgame/', abortgame),
    url(r'^union_account/', union_account),
    url(r'^union_account_list/', union_account_list),
    url(r'^club_account_view/', club_account_view),
    url(r'^club_cash/', club_cash),
    url(r'^union_check/', union_check),
    url(r'^result_detail/', result_detail),
    url(r'^group_balance_search/', group_balance_search),
    url(r'^group_balance_list/', group_balance_list),
    url(r'^company_account/', company_account),
    url(r'^getGroupAccount/', getGroupAccount),
    url(r'^company_cash/', company_cash),
    url(r'^company_balance_list/', company_balance_list),
    url(r'^getGameStatus/', getGameStatus),
    url(r'^loadsidebar/', loadsidebar),
    url(r'^correct_manage/', correct_manage),
    url(r'^correct_user_list/', correct_user_list),
    url(r'^correct_user/', correct_user),
    url(r'^correct_club_list/', correct_club_list),
    url(r'^correct_club/', correct_club),
    url(r'^correct_company_list/', correct_company_list),
    url(r'^correct_company/', correct_company),
    url(r'^loadnavigate/', loadnavigate),
    url(r'^company_income_manage/', company_income_manage),
    url(r'^company_income_reg/', company_income_reg),
    url(r'^developer_manage/', developer_manage),
    url(r'^developer_new/', developer_new),
    url(r'^check_developer/', check_developer),
    url(r'^developer_reg/', developer_reg),
    url(r'^developer_list/', developer_list),
    url(r'^developer_modify/', developer_modify),
    url(r'^developer_info/', developer_info),
    url(r'^developer_user/', developer_user),
    url(r'^developer_user_reg/', developer_user_reg),
    url(r'^developer_user_list/', developer_user_list),
    url(r'^developer_user_club_list/', developer_user_club_list),
    url(r'^developer_unband/', developer_unband),
    url(r'^app_initialize/', app_initialize),
    url(r'^app_union_setup/', app_union_setup),
    url(r'^load_main_club/', load_main_club),
    url(r'^welcome/', welcome),
    url(r'^app_operator/', app_operator),
    url(r'^app_operator_reg/', app_operator_reg),
    url(r'^result_list_view/', result_list_view),
    url(r'^result_list/', result_list),
    url(r'^developer_table_view/', developer_table_view),
    url(r'^developer_table_list/', developer_table_list),
    url(r'^developer_table_detail/', developer_table_detail),
    url(r'^result_detailbyClub/', result_detailbyClub),
    url(r'^report_developer/', report_developer),
    url(r'^report_developer_result/', report_developer_result),
    url(r'^reward_manage/', reward_manage),
    url(r'^reward_normal/', reward_normal),
    url(r'^reward_normal_add/', reward_normal_add),
    url(r'^reward_normal_list/', reward_normal_list),
    url(r'^reward_normal_modify/', reward_normal_modify),
    url(r'^reward_normal_delete/', reward_normal_delete),
    url(r'^reward_normal_form/', reward_normal_form),
    url(r'^reward_normal_reg/', reward_normal_reg),
    url(r'^deposit_rate/', deposit_rate),
    url(r'^deposit_rate_reg/', deposit_rate_reg),
    url(r'^depoist_rate_list/', depoist_rate_list),
    url(r'^depoist_rete_delete/', depoist_rete_delete),
    url(r'^deposit/', deposit),
    url(r'^get_deposit_rate/', get_deposit_rate),
    url(r'^deposit_reg/', deposit_reg),
    url(r'^deposit_list/', deposit_list),
    url(r'^manage_account_setup/', manage_account_setup),
    url(r'^manage_account_type_list/', manage_account_type_list),
    url(r'^manage_account_reg/', manage_account_reg),
    url(r'^manage_account_modify/', manage_account_modify),
    url(r'^deposit_arrived/', deposit_arrived),
    url(r'^user_detail/', user_detail),
    url(r'^user_balance_full_list/', user_balance_full_list),
    url(r'^user_result_full_list/', user_result_full_list),
    url(r'^user_freeze_full_list/', user_freeze_full_list),
    url(r'^user_income_full_list/', user_income_full_list),
    url(r'^warning/', warning),
    url(r'^permission/', permission),
    url(r'^permission_group/', permission_group),
    url(r'^get_permission_list/', get_permission_list),
    url(r'^permission_group_set/', permission_group_set),
    url(r'^permission_operator/', permission_operator),
    url(r'^permission_operator_list/', permission_operator_list),
    url(r'^operator_set_active/', operator_set_active),
    url(r'^operator_disable/', operator_disable),
    url(r'^change_password/', change_password),
    url(r'^new_password/', new_password),
    url(r'^reset_password/', reset_password),
    url(r'^set_password/', set_password),
    url(r'^upload_result_img/', upload_result_img),
    url(r'^result_img_show/', result_img_show),
    url(r'^user_result_min_list/', user_result_min_list),
    url(r'^credit_manage/', credit_manage),
    url(r'^load_credit_user_reg/', load_credit_user_reg),
    url(r'^load_credit_user_list/', load_credit_user_list),
    url(r'^credit_user_reg/', credit_user_reg),
    url(r'^credit_user_disable/', credit_user_disable),
    url(r'^credit_user_modify/', credit_user_modify),
    url(r'^load_credit_developer_reg/', load_credit_developer_reg),
    url(r'^credit_developer_reg/', credit_developer_reg),
    url(r'^load_credit_developer_list/', load_credit_developer_list),
    url(r'^credit_developer_disable/', credit_developer_disable),
    url(r'^credit_developer_modify/', credit_developer_modify),
    url(r'^check_developer_balance/', check_developer_balance),
    url(r'^check_developer_balance_by_user/', check_developer_balance_by_user),
    url(r'^union_balance_view/', union_balance_view),
    url(r'^developer_balance_view/', developer_balance_view),
    url(r'^developer_balance_cash/', developer_balance_cash),
    url(r'^developer_balance_list/', developer_balance_list),
    url(r'^operator_quick_view/', operator_quick_view),
    url(r'^user_balance_minus_list/', user_balance_minus_list),
    url(r'^developer_setup/', developer_setup),
    url(r'^developer_manage_reg/', developer_manage_reg),
    url(r'^developer_manage_list/', developer_manage_list),
    url(r'^logout/', logout),
    url(r'^correct_developer_list/', correct_developer_list),
    url(r'^correct_developer/', correct_developer),
    url(r'^correct_union_result_view/', correct_union_result_view),
    url(r'^correct_union_result/', correct_union_result),
    url(r'^correct_result/', correct_result),
    url(r'^search_correct_list/', search_correct_list),
    url(r'^correct_union_result_all/', correct_union_result_all),
    url(r'^result_detail_L2/', result_detail_L2),
    url(r'^correct_developer_view/', correct_developer_view),
    url(r'^correct_developer_result/', correct_developer_result),
    url(r'^result_list_pre/', result_list_pre),
    url(r'^search_correct_list_pre/', search_correct_list_pre),
    url(r'^add_user_exist_account/', add_user_exist_account),
    url(r'^union_check_club_view/', union_check_club_view),
    url(r'^union_check_union_view/', union_check_union_view),
    url(r'^union_check_balance_view/', union_check_balance_view),
    url(r'^union_check_club_balance_view/', union_check_club_balance_view),
    url(r'^club_check_result/', club_check_result),
    url(r'^club_check_result_search_balance/', club_check_result_search_balance),
    url(r'^club_check_result_search_game/', club_check_result_search_game),
    url(r'^init_club/', init_club),
    url(r'^init_load_user/', init_load_user),
    url(r'^init_user_cash/', init_user_cash),
    url(r'^init_load_user_balance_list/', init_load_user_balance_list),
    url(r'^init_load_club/', init_load_club),
    url(r'^init_club_cash/', init_club_cash),
    url(r'^init_union_balance_list/', init_union_balance_list),
    url(r'^init_load_operator/', init_load_operator),
    url(r'^init_operator_cash/', init_operator_cash),
    url(r'^init_operator_balance_list/', init_operator_balance_list),
    url(r'^init_developer_balance/', init_developer_balance),
    url(r'^init_developer_cash/', init_developer_cash),
    url(r'^test03/', test03),
    url(r'^upload_reward_img/', upload_reward_img),
    url(r'^load_reward_modal/', load_reward_modal),
    url(r'^reward/', reward),
    url(r'^reward_list/', reward_list),
    url(r'^init_income/', init_income),
    url(r'^init_income_reg/', init_income_reg),
    url(r'^manage_load_permission_menu/', manage_load_permission_menu),
    url(r'^get_treel2/', get_treel2),
    url(r'^modify_permission_menu/', modify_permission_menu),
    url(r'^union_user/', union_user),
    url(r'^load_union_user/', load_union_user),
    url(r'^union_muti_user_disable/', union_muti_user_disable),
    url(r'^load_union_user_all/', load_union_user_all),
    url(r'^union_check_disable/', union_check_disable),
    url(r'^reward_after/', reward_after),
    url(r'^disable_user_club/', disable_user_club),
    url(r'^check_exist_user_balance/', check_exist_user_balance),
    url(r'^club_check_statement/', club_check_statement),
    url(r'^club_check_result_get_union_balance/', club_check_result_get_union_balance),
    url(r'^result_l1_time/', result_l1_time),
    url(r'^correct_model/', correct_model),
    url(r'^user_full_list/', user_full_list),
    url(r'^result_inner_club/', result_inner_club),
    url(r'^get_inner_club_result/', get_inner_club_result),
    url(r'^get_club_income_by_date/', get_club_income_by_date),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
